// gen-icons.mjs — generates public/icons/*.png from an inline-HTML lettermark,
// screenshotted with Playwright (no image libs, no new deps). Run once and
// commit the resulting PNGs; public/icons/icon.svg is a separate hand-authored
// vector asset (not generated by this script) used for the SVG favicon link.
//
// Usage (Playwright is installed globally under Node 20, not the Node 24 used
// for `astro dev`/`npm run` — see scripts/layout-check.cjs's header comment
// for the same pattern):
//   N20=~/.nvm/versions/node/v20.20.2
//   NODE_PATH=$N20/lib/node_modules $N20/bin/node scripts/gen-icons.mjs
//
// Lettermark matches Sidebar.astro's .brand-mark: accent teal fill (compass
// light --accent, resolved to #008a6a from oklch(56% 0.12 170)), light glyph,
// bold "su". Two treatments:
//   - "rounded": baked-in rounded-square corners (~29% radius, matching the
//     Sidebar mark's 7px/24px ratio) — used for icon-192/icon-512, which
//     render as-is on platforms that don't apply their own icon mask.
//   - "full-bleed": edge-to-edge fill, no baked-in corner radius, glyph
//     scaled down to sit inside the ~80% "safe zone" that adaptive-icon
//     masks (Android maskable) and iOS's automatic squircle mask crop to —
//     used for icon-maskable-512 and apple-touch-icon.

import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const require = createRequire(import.meta.url);
const { chromium } = require('playwright');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const outDir = path.join(repoRoot, 'public', 'icons');

const FIGTREE_WOFF2 = path.join(
  repoRoot,
  'node_modules/@fontsource-variable/figtree/files/figtree-latin-wght-normal.woff2'
);

const ACCENT = '#008a6a'; // compass light --accent, oklch(56% 0.12 170)
const GLYPH = '#ffffff'; // compass light --surface, oklch(100% 0 0)

function html({ size, radius, fontSize }) {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  @font-face {
    font-family: 'Figtree Variable';
    src: url('file://${FIGTREE_WOFF2}') format('woff2-variations');
    font-weight: 100 900;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { width: ${size}px; height: ${size}px; background: transparent; }
  .icon {
    width: ${size}px;
    height: ${size}px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: ${ACCENT};
    border-radius: ${radius}px;
  }
  .glyph {
    font-family: 'Figtree Variable', 'Avenir Next', -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
    font-weight: 700;
    font-size: ${fontSize}px;
    letter-spacing: -0.02em;
    line-height: 1;
    color: ${GLYPH};
    transform: translateY(-0.03em);
  }
</style>
</head>
<body>
  <div class="icon"><span class="glyph">su</span></div>
</body>
</html>`;
}

const TARGETS = [
  { name: 'icon-192.png', size: 192, radius: Math.round(192 * 0.29), fontSize: Math.round(192 * 0.44) },
  { name: 'icon-512.png', size: 512, radius: Math.round(512 * 0.29), fontSize: Math.round(512 * 0.44) },
  { name: 'icon-maskable-512.png', size: 512, radius: 0, fontSize: Math.round(512 * 0.3) },
  { name: 'apple-touch-icon.png', size: 180, radius: 0, fontSize: Math.round(180 * 0.32) },
];

const browser = await chromium.launch();
const page = await browser.newPage({ deviceScaleFactor: 1 });

for (const t of TARGETS) {
  await page.setViewportSize({ width: t.size, height: t.size });
  await page.setContent(html(t), { waitUntil: 'load' });
  await page.evaluate(async () => {
    await document.fonts.ready;
  });
  const el = await page.$('.icon');
  await el.screenshot({ path: path.join(outDir, t.name), omitBackground: false });
  console.log(`wrote ${t.name} (${t.size}x${t.size}, radius ${t.radius}, font ${t.fontSize})`);
}

await browser.close();
