// Loads the generated McGill course catalogue into D1.
//
// courses/mcgill-catalog.json stays in the repo as the source of truth, but it
// is no longer imported by worker code: Vite inlined its ~10,000 rows as a
// JavaScript object literal, producing a 5 MB chunk that V8 parsed as source at
// every isolate start. The rows now live in `catalog_courses` plus the FTS5
// index `catalog_courses_fts` (migrations/0013_catalog_courses_in_d1.sql).
//
// Runs outside the Workers runtime (plain Node + tsx), so it shells out to
// `wrangler d1 execute` with generated SQL, matching scripts/seed.ts. The
// catalogue is replaced wholesale, so the script is idempotent.
//
//   npm run db:seed:catalog:local
//   npm run db:seed:catalog:remote
//   npx tsx scripts/seed-catalog.ts --remote --env staging
//   npx tsx scripts/seed-catalog.ts --fixture     # refresh the test fixture
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import {
  catalogCourseRow,
  catalogSearchText,
  type CatalogCourseRow,
  type RawCatalogCourse,
} from '../src/lib/content/catalogRows';

const CATALOG_PATH = join(process.cwd(), 'courses', 'mcgill-catalog.json');
const FIXTURE_PATH = join(process.cwd(), 'tests', 'fixtures', 'mcgill-catalog-sample.json');
// SQLite caps a VALUES clause at SQLITE_LIMIT_COMPOUND_SELECT (500) rows.
const ROWS_PER_INSERT = 200;

type CatalogFile = {
  schema_version: number;
  institution: string;
  catalog_year?: string;
  generated_from?: string;
  columns: unknown;
  courses: RawCatalogCourse[];
};

function sqlStr(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlNum(value: number | null): string {
  return value === null ? 'NULL' : String(value);
}

function insertStatements(rows: CatalogCourseRow[]): string[] {
  const statements = ['DELETE FROM catalog_courses;', 'DELETE FROM catalog_courses_fts;'];
  for (let start = 0; start < rows.length; start += ROWS_PER_INSERT) {
    const batch = rows.slice(start, start + ROWS_PER_INSERT);
    statements.push(
      'INSERT INTO catalog_courses (id, slug, code, title, credits, department, faculty, audience, kcs, kc_count, normalized_code, compact_code, normalized_title, sort_key) VALUES '
      + batch.map((row) => `(${row.id}, ${sqlStr(row.slug)}, ${sqlStr(row.code)}, ${sqlStr(row.title)}, ${sqlNum(row.credits)}, ${sqlStr(row.department)}, ${sqlStr(row.faculty)}, ${sqlStr(row.audience)}, ${sqlStr(JSON.stringify(row.kcs))}, ${row.kcs.length}, ${sqlStr(row.normalizedCode)}, ${sqlStr(row.compactCode)}, ${sqlStr(row.normalizedTitle)}, ${sqlStr(row.sortKey)})`).join(', ')
      + ';',
    );
    statements.push(
      'INSERT INTO catalog_courses_fts (rowid, search_text) VALUES '
      + batch.map((row) => `(${row.id}, ${sqlStr(catalogSearchText(row))})`).join(', ')
      + ';',
    );
  }
  return statements;
}

/**
 * A deterministic slice of the catalogue for the Workers test pool, which
 * applies migrations per test file and would spend seconds inserting all
 * ~10,000 rows into every one of them. It keeps the populations the catalogue
 * tests actually assert on — every COMP and ACCT course, the concept-search
 * targets, and one course from every subject for breadth — so search ranking,
 * numeric code ordering, level filtering and slug lookup all stay covered.
 */
function fixtureCourses(courses: RawCatalogCourse[]): RawCatalogCourse[] {
  const searchText = (course: RawCatalogCourse) =>
    catalogSearchText(catalogCourseRow(course, 0));
  const conceptQueries = [['photosynthesis'], ['supply', 'demand'], ['programming', 'variables']];
  const selected = new Set<RawCatalogCourse>();
  const seenSubjects = new Set<string>();
  for (const course of courses) {
    const subject = course[0].split(' ')[0];
    const text = searchText(course);
    const wanted = subject === 'COMP'
      || subject === 'ACCT'
      || conceptQueries.some((terms) => terms.every((term) => text.includes(term)))
      || !seenSubjects.has(subject);
    seenSubjects.add(subject);
    if (wanted) selected.add(course);
  }
  // Source order, so the fixture is a stable diff when the catalogue is rebuilt.
  return courses.filter((course) => selected.has(course));
}

function writeFixture(catalog: CatalogFile): void {
  const courses = fixtureCourses(catalog.courses);
  mkdirSync(dirname(FIXTURE_PATH), { recursive: true });
  writeFileSync(FIXTURE_PATH, `${JSON.stringify({
    // Generated by `npx tsx scripts/seed-catalog.ts --fixture`. Do not edit.
    generated_by: 'scripts/seed-catalog.ts --fixture',
    generated_from: 'courses/mcgill-catalog.json',
    // The size of the catalogue this sample was drawn from, so tests can still
    // assert that the pipeline carries the whole ~10,000-course catalogue.
    source_total: catalog.courses.length,
    columns: catalog.columns,
    courses,
  }, null, 0)}\n`);
  console.log(`Wrote ${courses.length} of ${catalog.courses.length} courses to ${FIXTURE_PATH}`);
}

function main(): void {
  const catalog: CatalogFile = JSON.parse(readFileSync(CATALOG_PATH, 'utf-8'));

  if (process.argv.includes('--fixture')) {
    writeFixture(catalog);
    return;
  }

  const isRemote = process.argv.includes('--remote');
  const dbFlag = isRemote ? '--remote' : '--local';
  const envFlagIndex = process.argv.indexOf('--env');
  const wranglerEnv = envFlagIndex === -1 ? undefined : process.argv[envFlagIndex + 1];
  if (envFlagIndex !== -1 && (!wranglerEnv || wranglerEnv.startsWith('--'))) {
    throw new Error('--env requires a Wrangler environment name.');
  }

  const rows = catalog.courses.map((course, index) => catalogCourseRow(course, index + 1));
  const dir = mkdtempSync(join(tmpdir(), 'studyus-catalog-'));
  const sqlPath = join(dir, 'catalog.sql');
  // ~7 MB of SQL. `wrangler d1 execute --remote --file` uploads it and lets D1
  // ingest it server-side, so size is not a constraint the way --command is.
  const sqlText = insertStatements(rows).join('\n');
  writeFileSync(sqlPath, sqlText);

  execFileSync(
    'npx',
    [
      'wrangler',
      'd1',
      'execute',
      'DB',
      dbFlag,
      ...(wranglerEnv ? ['--env', wranglerEnv] : []),
      '--file',
      sqlPath,
    ],
    { stdio: 'inherit' },
  );

  console.log(`Seeded ${rows.length} catalogue courses from ${(sqlText.length / 1e6).toFixed(1)} MB of SQL (${dbFlag}).`);
}

main();
